kind: Service
apiVersion: v1
metadata:
  name: particles
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
    name: http
  selector:
    app: particles
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: particles-v1.0.0
spec:
  selector:
    matchLabels:
      app: particles
  replicas: 1
  template:
    metadata:
      labels:
        app: particles
        version: 1.0.0
    spec:
      containers:
      - name: particles
        image: magneticio/particles
        imagePullPolicy: Always
        args:
          - "--color=#F0F5FA"
          - "--appVersion=v1.0.0"
          - "--showStats"
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          requests:
            cpu: 0.25
            memory: 512
